apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: env-printer-file
  name: env-printer-file
  namespace: test-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: env-printer-file
  template:
    metadata:
      labels:
        app: env-printer-file
      annotations:
        conjur.org/container-mode: sidecar
        conjur.org/secrets-destination: file
        conjur.org/jwt-token-path: /var/run/secrets/tokens/jwt
        conjur.org/conjur-secrets.env-printer-file: |
          - admin-username: data/vault/Karthik-test-conjur/conjur-account-name/username
          - admin-password: data/vault/Karthik-test-conjur/conjur-account-name/password
          - db-address: data/vault/Karthik-test-conjur/conjur-account-name/address
          - db-domain: data/vault/Karthik-test-conjur/conjur-account-name/Domain
        conjur.org/secret-file-path.env-printer-file: "./credentials.yaml"
        conjur.org/secret-file-format.env-printer-file: "yaml"
        conjur.org/secrets-refresh-interval: 10s
    spec:
      serviceAccountName: test-app-sa
      containers:
      - name: env-printer-file
        image: uperformkarthick/env-printer:latest
        volumeMounts:
          - name: conjur-secrets
            mountPath: /opt/secrets/conjur
            readOnly: true
      - name: cyberark-secrets-provider-for-k8s
        image: 'cyberark/secrets-provider-for-k8s:latest'
        imagePullPolicy: Always
        volumeMounts:
        - name: conjur-status
          mountPath: /conjur/status
        - name: podinfo
          mountPath: /conjur/podinfo
        - name: conjur-secrets
          mountPath: /conjur/
        - name: jwt-token
          mountPath: /var/run/secrets/tokens
        env:
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        envFrom:
          - configMapRef:
              name: conjur-connect
      volumes:
        - name: conjur-status
          emptyDir:
            medium: Memory
        - name: podinfo
          downwardAPI:
            items:
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
        - name: conjur-secrets
          emptyDir:
            medium: Memory
        - name: jwt-token
          projected:
            sources:
              - serviceAccountToken:
                  path: jwt
                  expirationSeconds: 6000
                  audience: conjur