apiVersion: v1
kind: Secret
metadata:
  name: sample-secret
  namespace: test-app-namespace
type: Opaque
data:
  dbname: a2FydGhpa2t1YmVkYXRhYmFzZQ==
  username: YWRtaW4=  # Base64 encoded value of "username"
  password: Q3liZXJhcmsx  # Base64 encoded value of "password"