apiVersion: v1
kind: Service
metadata:
  name: env-printer-service
  namespace: test-app-namespace
spec:
  selector:
    app: env-printer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30007
  type: NodePort